services:
  docs:
    container_name: taskerha-docs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: nginx-proxy-manager_default  # replace with your actual NPM network name
